% ClinicalCNL v1 surface goldens — replayer + capture (M3.surface-goldens; SPEC §10.6).
%
% The gate re-runs every seed in goldens/surface_cases.pl through the canonical APE product
% seam and asserts, byte-exact, the content-type + serialized DRS + message list recorded in
% goldens/surface_expected.pl (captured OBSERVED, never hand-written). It also asserts the
% per-kind invariants — reject iff text/xml; v1/nonv1 both text/plain; the v1 fail-closed
% zero-message law (a v1-admissible surface emits NO messages). It pins the v1 surface
% feasibility every downstream unit (raw-gate, profile-drs, map-*) builds on.
%
%   Gate:       swipl -q -g "consult('clinical/surface_goldens.pl'), (run_tests(surface_goldens)->halt(0);halt(1))" -t 'halt(1)'
%   Regenerate: swipl -q -g "consult('clinical/surface_goldens.pl'), surface_goldens:capture, halt" -t 'halt(1)'
%
% Canonical seam (SURFACE.md §seam): get_ape_results with noclex=on (ulex-only, hard-error on
% an unregistered lowercase word), guess=off, solo=drs (serialized DRS = the golden byte
% format). text/plain + DRS = APE parse; text/xml <messages> = APE reject. The seam DROPS
% warnings (solo mode keeps only error messages), so run_seam reads the full message list
% from the error_logger store after each call — that message list is a first-class golden and
% the substrate of the zero-message law (an accepted v1 surface must be warning-free).

:- module(surface_goldens, [run_seam/4, capture/0]).

:- use_module(library(plunit)).

:- dynamic surface_goldens_dir/1.

% Bootstrap the APE env + case seeds + goldens, all source-relative (cwd-independent):
% prolog/ape.pl asserts an absolute `ape` file_search_path when get_ape_results.pl loads it.
:- prolog_load_context(directory, D),
   asserta(surface_goldens_dir(D)),
   atomic_list_concat([D, '/../get_ape_results.pl'], Ape), ensure_loaded(Ape),
   atomic_list_concat([D, '/goldens/surface_cases.pl'], Cases), use_module(Cases),
   atomic_list_concat([D, '/goldens/surface_expected.pl'], Exp),
   ( exists_file(Exp) -> use_module(Exp) ; true ).

%% run_seam(+ACE:atom, -ContentType:atom, -Content:atom, -Messages:list) is det.
% The canonical ClinicalCNL APE invocation, plus the full message list the seam would drop.
% Deterministic. get_ape_results clears the message store at entry and never at exit, so the
% store holds exactly this parse's messages afterward.
run_seam(ACE, ContentType, Content, Messages) :-
    surface_ulex(Ulex),
    ape:get_ape_results([text=ACE, noclex=on, ulextext=Ulex, guess=off, solo=drs],
                        ContentType, Content),
    error_logger:get_messages(Messages).

%% kind_content_type(?Kind:atom, ?ContentType:atom) is det.
% v1 and nonv1 both parse (text/plain); reject fails closed (text/xml).
kind_content_type(v1,     'text/plain').
kind_content_type(nonv1,  'text/plain').
kind_content_type(reject, 'text/xml').

%% capture is det.
% (Re)generate goldens/surface_expected.pl from the live seam. Deterministic writer: one
% ~q-quoted fact per case in surface_case/3 order; regeneration is idempotent.
capture :-
    surface_goldens_dir(D),
    atomic_list_concat([D, '/goldens/surface_expected.pl'], Exp),
    setup_call_cleanup(
        open(Exp, write, S),
        ( format(S, '% GENERATED by surface_goldens:capture — do not edit. Observed product-seam~n', []),
          format(S, '% content-type + serialized DRS + message list per goldens/surface_cases.pl~n', []),
          format(S, '% case. Regenerate, never hand-edit.~n~n', []),
          format(S, ':- module(surface_expected, [surface_expected/4]).~n~n', []),
          forall(surface_cases:surface_case(Id, _Kind, ACE),
                 ( run_seam(ACE, CT, Content, Msgs),
                   format(S, '~q.~n', [surface_expected(Id, CT, Content, Msgs)]) )) ),
        close(S)).

:- begin_tests(surface_goldens).

% Each case: content-type matches its kind; a v1 surface emits zero messages (fail-closed
% law); and content-type, serialized bytes, and message list all match the committed golden.
test(golden, [forall(surface_cases:surface_case(Id, Kind, ACE))]) :-
    run_seam(ACE, CT, Content, Msgs),
    kind_content_type(Kind, KindCT),
    assertion(CT == KindCT),
    ( Kind == v1 -> assertion(Msgs == []) ; true ),
    ( surface_expected:surface_expected(Id, ExpCT, ExpContent, ExpMsgs)
    -> assertion(CT == ExpCT),
       assertion(Content == ExpContent),
       assertion(Msgs == ExpMsgs)
    ;  format(user_error, "surface_goldens: no golden for ~w (run capture)~n", [Id]),
       fail ).

:- end_tests(surface_goldens).
