% ClinicalCNL v1 surface goldens — replayer + capture (M3.surface-goldens; SPEC §10.6).
%
% The gate re-runs every seed in goldens/surface_cases.pl through the canonical APE product
% seam and asserts, byte-exact, the content-type + serialized bytes recorded in
% goldens/surface_expected.pl (captured OBSERVED, never hand-written). It pins the v1 surface
% feasibility every downstream unit (raw-gate, profile-drs, map-*) builds on.
%
%   Gate:       swipl -q -g "consult('clinical/surface_goldens.pl'), (run_tests(surface_goldens)->halt(0);halt(1))" -t 'halt(1)'
%   Regenerate: swipl -q -g "consult('clinical/surface_goldens.pl'), surface_goldens:capture, halt" -t 'halt(1)'
%
% Canonical seam (SURFACE.md §seam): get_ape_results with noclex=on (ulex-only, fail-closed on
% OOV), guess=off (no proper-name guessing, fail-closed on capitalised OOV), solo=drs (serialized
% DRS = the golden byte format). text/plain + DRS = parse; text/xml <messages> = APE reject.

:- module(surface_goldens, [run_seam/3, capture/0]).

:- use_module(library(plunit)).

:- dynamic surface_goldens_dir/1.

% Bootstrap the APE env + case seeds + goldens, all source-relative (cwd-independent):
% prolog/ape.pl asserts an absolute `ape` file_search_path when get_ape_results.pl loads it.
:- prolog_load_context(directory, D),
   asserta(surface_goldens_dir(D)),
   atomic_list_concat([D, '/../get_ape_results.pl'], Ape), ensure_loaded(Ape),
   atomic_list_concat([D, '/goldens/surface_cases.pl'], Cases), use_module(Cases),
   atomic_list_concat([D, '/goldens/surface_expected.pl'], Exp),
   ( exists_file(Exp) -> use_module(Exp) ; true ).

%% run_seam(+ACE:atom, -ContentType:atom, -Content:atom) is det.
% The canonical ClinicalCNL APE invocation. Deterministic + fail-closed.
run_seam(ACE, ContentType, Content) :-
    surface_ulex(Ulex),
    ape:get_ape_results([text=ACE, noclex=on, ulextext=Ulex, guess=off, solo=drs],
                        ContentType, Content).

%% kind_content_type(?Kind:atom, ?ContentType:atom) is det.
kind_content_type(parses,   'text/plain').
kind_content_type(rejected, 'text/xml').

%% capture is det.
% (Re)generate goldens/surface_expected.pl from the live seam. Deterministic writer: one
% ~q-quoted fact per case in surface_case/3 order; regeneration is idempotent.
capture :-
    surface_goldens_dir(D),
    atomic_list_concat([D, '/goldens/surface_expected.pl'], Exp),
    setup_call_cleanup(
        open(Exp, write, S),
        ( format(S, '% GENERATED by surface_goldens:capture — do not edit. Observed product-seam~n', []),
          format(S, '% bytes for each goldens/surface_cases.pl case. Regenerate, never hand-edit.~n~n', []),
          format(S, ':- module(surface_expected, [surface_expected/3]).~n~n', []),
          forall(surface_cases:surface_case(Id, _Kind, ACE),
                 ( run_seam(ACE, CT, Content),
                   format(S, '~q.~n', [surface_expected(Id, CT, Content)]) )) ),
        close(S)).

:- begin_tests(surface_goldens).

% Each case: content-type matches its declared kind, and both content-type and serialized
% bytes match the committed golden exactly.
test(golden, [forall(surface_cases:surface_case(Id, Kind, ACE))]) :-
    run_seam(ACE, CT, Content),
    kind_content_type(Kind, KindCT),
    assertion(CT == KindCT),
    ( surface_expected:surface_expected(Id, ExpCT, ExpContent)
    -> assertion(CT == ExpCT),
       assertion(Content == ExpContent)
    ;  format(user_error, "surface_goldens: no golden for ~w (run capture)~n", [Id]),
       fail ).

:- end_tests(surface_goldens).
